# fly.toml app configuration file generated for replane-cloud-prod on 2025-12-27T20:41:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'replane-cloud-prod'
primary_region = 'iad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    soft_limit = 1000

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"

[env]
  BASE_URL = "https://cloud.replane.dev"
  PORT = "8080"
  SWAP_SIZE = "2048M"

  # pgbouncer allows 200 max connections, we deploy 6 replicas = 200 / 6 ~= 30
  DATABASE_MAX_CONNECTIONS = "30"

  EMAIL_FROM = "noreply@replane.dev"

  MAGIC_LINK_ENABLED = "true"

  SENTRY_DSN = "https://91b9a5d0d1dca2615d6f3fbc085d1dc8@o4510523200503808.ingest.de.sentry.io/4510523212431440"
  SENTRY_ENVIRONMENT = "production"
  SENTRY_TRACES_SAMPLE_RATE = "0.1"

  REPLANE_BASE_URL = "https://cloud.replane.dev"
  REPLANE_SDK_KEY = "rp_bc00ae4689b434600899a6f244f286608ba357ad740b3126019b62195e6877b99b6476a2cbe16ad2"

  # we also use fly.io secrets for variables like EMAIL_SERVER/GITHUB_CLIENT_SECRET/etc

[[vm]]
  cpus = 2
  cpu_kind = "performance"
  memory = '4gb'

[metrics]
  port = 8080
  path = "/metrics"
